DELETE http://localhost:8090/events/6
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFua3VyQHlvcG1haWwuY29tIiwiZXhwIjoxNzY3OTQ5NjI5LCJ1c2VySWQiOjJ9.G1kRmT7rspfrSZ3YjphbTeNAjvt_huSEEB1mvrBuTaE
